version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DB_ENDPOINT: "mongodb://mongodb:27017"
    ports:
      - 3000:3000
    links:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./backend/db:/data/db
