version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DB_ENDPOINT: "${DB_ENDPOINT}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_AUTH_ON: "${DB_AUTH_ON}"
      FEATURES_BATCH_SIZE: "${FEATURES_BATCH_SIZE}"
      FEATURES_BATCH_DELAY: "${FEATURES_BATCH_DELAY}"
      FEATURES_UNIT_DELAY: "${FEATURES_UNIT_DELAY}"
      FEATURES_CURRENT_PLAYERS_UPDATE_INTERVAL_DELAY: "${FEATURES_CURRENT_PLAYERS_UPDATE_INTERVAL_DELAY}"
      FEATURES_UPDATE_INTERVAL_DELAY: "${FEATURES_UPDATE_INTERVAL_DELAY}"
      FEATURES_ITERATION_DELAY: "${FEATURES_ITERATION_DELAY}"
      RUNNER_ITERATION_DELAY: "${RUNNER_ITERATION_DELAY}"
    ports:
      - 3000:3000
    links:
      - mongodb

  mongodb:
    image: mongo:4.4.24
    container_name: mongodb
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
      - ./db/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh:ro
