name: Build container and push to registry.

on:
  push:
    branches: [master]
    paths: ["backend/**"]
  pull_request:
    branches: [master]
    paths: ["backend/**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/Dockerfile
          tags: sjakusch/steam-game-stats-backend:latest
